// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/thebeyond-net/node-agent/pkg/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ControlPlaneServiceName is the fully-qualified name of the ControlPlaneService service.
	ControlPlaneServiceName = "agent.v1.ControlPlaneService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ControlPlaneServiceConnectProcedure is the fully-qualified name of the ControlPlaneService's
	// Connect RPC.
	ControlPlaneServiceConnectProcedure = "/agent.v1.ControlPlaneService/Connect"
	// ControlPlaneServiceSyncProcedure is the fully-qualified name of the ControlPlaneService's Sync
	// RPC.
	ControlPlaneServiceSyncProcedure = "/agent.v1.ControlPlaneService/Sync"
)

// ControlPlaneServiceClient is a client for the agent.v1.ControlPlaneService service.
type ControlPlaneServiceClient interface {
	Connect(context.Context) (*connect.BidiStreamForClientSimple[v1.AgentMessage, v1.ControlCommand], error)
	Sync(context.Context, *v1.SyncRequest) (*v1.SyncResponse, error)
}

// NewControlPlaneServiceClient constructs a client for the agent.v1.ControlPlaneService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControlPlaneServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControlPlaneServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	controlPlaneServiceMethods := v1.File_agent_proto.Services().ByName("ControlPlaneService").Methods()
	return &controlPlaneServiceClient{
		connect: connect.NewClient[v1.AgentMessage, v1.ControlCommand](
			httpClient,
			baseURL+ControlPlaneServiceConnectProcedure,
			connect.WithSchema(controlPlaneServiceMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		sync: connect.NewClient[v1.SyncRequest, v1.SyncResponse](
			httpClient,
			baseURL+ControlPlaneServiceSyncProcedure,
			connect.WithSchema(controlPlaneServiceMethods.ByName("Sync")),
			connect.WithClientOptions(opts...),
		),
	}
}

// controlPlaneServiceClient implements ControlPlaneServiceClient.
type controlPlaneServiceClient struct {
	connect *connect.Client[v1.AgentMessage, v1.ControlCommand]
	sync    *connect.Client[v1.SyncRequest, v1.SyncResponse]
}

// Connect calls agent.v1.ControlPlaneService.Connect.
func (c *controlPlaneServiceClient) Connect(ctx context.Context) (*connect.BidiStreamForClientSimple[v1.AgentMessage, v1.ControlCommand], error) {
	return c.connect.CallBidiStreamSimple(ctx)
}

// Sync calls agent.v1.ControlPlaneService.Sync.
func (c *controlPlaneServiceClient) Sync(ctx context.Context, req *v1.SyncRequest) (*v1.SyncResponse, error) {
	response, err := c.sync.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ControlPlaneServiceHandler is an implementation of the agent.v1.ControlPlaneService service.
type ControlPlaneServiceHandler interface {
	Connect(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ControlCommand]) error
	Sync(context.Context, *v1.SyncRequest) (*v1.SyncResponse, error)
}

// NewControlPlaneServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControlPlaneServiceHandler(svc ControlPlaneServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controlPlaneServiceMethods := v1.File_agent_proto.Services().ByName("ControlPlaneService").Methods()
	controlPlaneServiceConnectHandler := connect.NewBidiStreamHandler(
		ControlPlaneServiceConnectProcedure,
		svc.Connect,
		connect.WithSchema(controlPlaneServiceMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	controlPlaneServiceSyncHandler := connect.NewUnaryHandlerSimple(
		ControlPlaneServiceSyncProcedure,
		svc.Sync,
		connect.WithSchema(controlPlaneServiceMethods.ByName("Sync")),
		connect.WithHandlerOptions(opts...),
	)
	return "/agent.v1.ControlPlaneService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControlPlaneServiceConnectProcedure:
			controlPlaneServiceConnectHandler.ServeHTTP(w, r)
		case ControlPlaneServiceSyncProcedure:
			controlPlaneServiceSyncHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControlPlaneServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedControlPlaneServiceHandler struct{}

func (UnimplementedControlPlaneServiceHandler) Connect(context.Context, *connect.BidiStream[v1.AgentMessage, v1.ControlCommand]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.ControlPlaneService.Connect is not implemented"))
}

func (UnimplementedControlPlaneServiceHandler) Sync(context.Context, *v1.SyncRequest) (*v1.SyncResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("agent.v1.ControlPlaneService.Sync is not implemented"))
}
