// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_AMNEZIA_WG  Protocol = 1
	Protocol_PROTOCOL_VLESS       Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_AMNEZIA_WG",
		2: "PROTOCOL_VLESS",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_AMNEZIA_WG":  1,
		"PROTOCOL_VLESS":       2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerConfig          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetPeers() []*PeerConfig {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=agent.v1.Protocol" json:"protocol,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerConfig) Reset() {
	*x = PeerConfig{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConfig) ProtoMessage() {}

func (x *PeerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConfig.ProtoReflect.Descriptor instead.
func (*PeerConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PeerConfig) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *PeerConfig) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*AgentMessage_Status
	//	*AgentMessage_CommandResponse
	Content       isAgentMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentMessage) GetContent() isAgentMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentMessage) GetStatus() *AgentStatus {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetCommandResponse() *CommandResponse {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_CommandResponse); ok {
			return x.CommandResponse
		}
	}
	return nil
}

type isAgentMessage_Content interface {
	isAgentMessage_Content()
}

type AgentMessage_Status struct {
	Status *AgentStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type AgentMessage_CommandResponse struct {
	CommandResponse *CommandResponse `protobuf:"bytes,3,opt,name=command_response,json=commandResponse,proto3,oneof"`
}

func (*AgentMessage_Status) isAgentMessage_Content() {}

func (*AgentMessage_CommandResponse) isAgentMessage_Content() {}

type ControlCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*ControlCommand_CreatePeer
	//	*ControlCommand_DeletePeer
	//	*ControlCommand_SetBandwidth
	//	*ControlCommand_HealthCheck
	Action        isControlCommand_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ControlCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ControlCommand) GetAction() isControlCommand_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ControlCommand) GetCreatePeer() *CreatePeerRequest {
	if x != nil {
		if x, ok := x.Action.(*ControlCommand_CreatePeer); ok {
			return x.CreatePeer
		}
	}
	return nil
}

func (x *ControlCommand) GetDeletePeer() *DeletePeerRequest {
	if x != nil {
		if x, ok := x.Action.(*ControlCommand_DeletePeer); ok {
			return x.DeletePeer
		}
	}
	return nil
}

func (x *ControlCommand) GetSetBandwidth() *SetPeerBandwidthRequest {
	if x != nil {
		if x, ok := x.Action.(*ControlCommand_SetBandwidth); ok {
			return x.SetBandwidth
		}
	}
	return nil
}

func (x *ControlCommand) GetHealthCheck() *HealthCheckRequest {
	if x != nil {
		if x, ok := x.Action.(*ControlCommand_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

type isControlCommand_Action interface {
	isControlCommand_Action()
}

type ControlCommand_CreatePeer struct {
	CreatePeer *CreatePeerRequest `protobuf:"bytes,2,opt,name=create_peer,json=createPeer,proto3,oneof"`
}

type ControlCommand_DeletePeer struct {
	DeletePeer *DeletePeerRequest `protobuf:"bytes,3,opt,name=delete_peer,json=deletePeer,proto3,oneof"`
}

type ControlCommand_SetBandwidth struct {
	SetBandwidth *SetPeerBandwidthRequest `protobuf:"bytes,4,opt,name=set_bandwidth,json=setBandwidth,proto3,oneof"`
}

type ControlCommand_HealthCheck struct {
	HealthCheck *HealthCheckRequest `protobuf:"bytes,5,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

func (*ControlCommand_CreatePeer) isControlCommand_Action() {}

func (*ControlCommand_DeletePeer) isControlCommand_Action() {}

func (*ControlCommand_SetBandwidth) isControlCommand_Action() {}

func (*ControlCommand_HealthCheck) isControlCommand_Action() {}

type CommandResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Success      bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*CommandResponse_CreateResponse
	//	*CommandResponse_DeleteResponse
	//	*CommandResponse_BandwidthResponse
	Data          isCommandResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResponse) GetData() isCommandResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandResponse) GetCreateResponse() *CreatePeerResponse {
	if x != nil {
		if x, ok := x.Data.(*CommandResponse_CreateResponse); ok {
			return x.CreateResponse
		}
	}
	return nil
}

func (x *CommandResponse) GetDeleteResponse() *DeletePeerResponse {
	if x != nil {
		if x, ok := x.Data.(*CommandResponse_DeleteResponse); ok {
			return x.DeleteResponse
		}
	}
	return nil
}

func (x *CommandResponse) GetBandwidthResponse() *SetPeerBandwidthResponse {
	if x != nil {
		if x, ok := x.Data.(*CommandResponse_BandwidthResponse); ok {
			return x.BandwidthResponse
		}
	}
	return nil
}

type isCommandResponse_Data interface {
	isCommandResponse_Data()
}

type CommandResponse_CreateResponse struct {
	CreateResponse *CreatePeerResponse `protobuf:"bytes,3,opt,name=create_response,json=createResponse,proto3,oneof"`
}

type CommandResponse_DeleteResponse struct {
	DeleteResponse *DeletePeerResponse `protobuf:"bytes,4,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type CommandResponse_BandwidthResponse struct {
	BandwidthResponse *SetPeerBandwidthResponse `protobuf:"bytes,5,opt,name=bandwidth_response,json=bandwidthResponse,proto3,oneof"`
}

func (*CommandResponse_CreateResponse) isCommandResponse_Data() {}

func (*CommandResponse_DeleteResponse) isCommandResponse_Data() {}

func (*CommandResponse_BandwidthResponse) isCommandResponse_Data() {}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivePeers   int32                  `protobuf:"varint,1,opt,name=active_peers,json=activePeers,proto3" json:"active_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentStatus) GetActivePeers() int32 {
	if x != nil {
		return x.ActivePeers
	}
	return 0
}

type CreatePeerRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Protocol  Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=agent.v1.Protocol" json:"protocol,omitempty"`
	Bandwidth int32                  `protobuf:"varint,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Types that are valid to be assigned to Options:
	//
	//	*CreatePeerRequest_VlessOptions
	Options       isCreatePeerRequest_Options `protobuf_oneof:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeerRequest) Reset() {
	*x = CreatePeerRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerRequest) ProtoMessage() {}

func (x *CreatePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerRequest.ProtoReflect.Descriptor instead.
func (*CreatePeerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePeerRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *CreatePeerRequest) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *CreatePeerRequest) GetOptions() isCreatePeerRequest_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreatePeerRequest) GetVlessOptions() *VLESSOptions {
	if x != nil {
		if x, ok := x.Options.(*CreatePeerRequest_VlessOptions); ok {
			return x.VlessOptions
		}
	}
	return nil
}

type isCreatePeerRequest_Options interface {
	isCreatePeerRequest_Options()
}

type CreatePeerRequest_VlessOptions struct {
	VlessOptions *VLESSOptions `protobuf:"bytes,3,opt,name=vless_options,json=vlessOptions,proto3,oneof"`
}

func (*CreatePeerRequest_VlessOptions) isCreatePeerRequest_Options() {}

type VLESSOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VLESSOptions) Reset() {
	*x = VLESSOptions{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VLESSOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLESSOptions) ProtoMessage() {}

func (x *VLESSOptions) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLESSOptions.ProtoReflect.Descriptor instead.
func (*VLESSOptions) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *VLESSOptions) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePeerResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*CreatePeerResponse_VlessData
	//	*CreatePeerResponse_AwgData
	Data          isCreatePeerResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeerResponse) Reset() {
	*x = CreatePeerResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerResponse) ProtoMessage() {}

func (x *CreatePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerResponse.ProtoReflect.Descriptor instead.
func (*CreatePeerResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePeerResponse) GetData() isCreatePeerResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreatePeerResponse) GetVlessData() *VLESSResponse {
	if x != nil {
		if x, ok := x.Data.(*CreatePeerResponse_VlessData); ok {
			return x.VlessData
		}
	}
	return nil
}

func (x *CreatePeerResponse) GetAwgData() *AmneziaWGResponse {
	if x != nil {
		if x, ok := x.Data.(*CreatePeerResponse_AwgData); ok {
			return x.AwgData
		}
	}
	return nil
}

type isCreatePeerResponse_Data interface {
	isCreatePeerResponse_Data()
}

type CreatePeerResponse_VlessData struct {
	VlessData *VLESSResponse `protobuf:"bytes,2,opt,name=vless_data,json=vlessData,proto3,oneof"`
}

type CreatePeerResponse_AwgData struct {
	AwgData *AmneziaWGResponse `protobuf:"bytes,3,opt,name=awg_data,json=awgData,proto3,oneof"`
}

func (*CreatePeerResponse_VlessData) isCreatePeerResponse_Data() {}

func (*CreatePeerResponse_AwgData) isCreatePeerResponse_Data() {}

type VLESSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Sni           string                 `protobuf:"bytes,4,opt,name=sni,proto3" json:"sni,omitempty"`
	Pbk           string                 `protobuf:"bytes,5,opt,name=pbk,proto3" json:"pbk,omitempty"`
	Sid           string                 `protobuf:"bytes,6,opt,name=sid,proto3" json:"sid,omitempty"`
	Fp            string                 `protobuf:"bytes,7,opt,name=fp,proto3" json:"fp,omitempty"`
	Transport     string                 `protobuf:"bytes,8,opt,name=transport,proto3" json:"transport,omitempty"`
	Path          string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	Host          string                 `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
	Mode          string                 `protobuf:"bytes,11,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VLESSResponse) Reset() {
	*x = VLESSResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VLESSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VLESSResponse) ProtoMessage() {}

func (x *VLESSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VLESSResponse.ProtoReflect.Descriptor instead.
func (*VLESSResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *VLESSResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VLESSResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VLESSResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *VLESSResponse) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *VLESSResponse) GetPbk() string {
	if x != nil {
		return x.Pbk
	}
	return ""
}

func (x *VLESSResponse) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *VLESSResponse) GetFp() string {
	if x != nil {
		return x.Fp
	}
	return ""
}

func (x *VLESSResponse) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *VLESSResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *VLESSResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VLESSResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type AmneziaWGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Jc            int32                  `protobuf:"varint,5,opt,name=jc,proto3" json:"jc,omitempty"`
	Jmin          int32                  `protobuf:"varint,6,opt,name=jmin,proto3" json:"jmin,omitempty"`
	Jmax          int32                  `protobuf:"varint,7,opt,name=jmax,proto3" json:"jmax,omitempty"`
	S1            int32                  `protobuf:"varint,8,opt,name=s1,proto3" json:"s1,omitempty"`
	S2            int32                  `protobuf:"varint,9,opt,name=s2,proto3" json:"s2,omitempty"`
	H1            int32                  `protobuf:"varint,10,opt,name=h1,proto3" json:"h1,omitempty"`
	H2            int32                  `protobuf:"varint,11,opt,name=h2,proto3" json:"h2,omitempty"`
	H3            int32                  `protobuf:"varint,12,opt,name=h3,proto3" json:"h3,omitempty"`
	H4            int32                  `protobuf:"varint,13,opt,name=h4,proto3" json:"h4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmneziaWGResponse) Reset() {
	*x = AmneziaWGResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmneziaWGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmneziaWGResponse) ProtoMessage() {}

func (x *AmneziaWGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmneziaWGResponse.ProtoReflect.Descriptor instead.
func (*AmneziaWGResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AmneziaWGResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *AmneziaWGResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *AmneziaWGResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AmneziaWGResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AmneziaWGResponse) GetJc() int32 {
	if x != nil {
		return x.Jc
	}
	return 0
}

func (x *AmneziaWGResponse) GetJmin() int32 {
	if x != nil {
		return x.Jmin
	}
	return 0
}

func (x *AmneziaWGResponse) GetJmax() int32 {
	if x != nil {
		return x.Jmax
	}
	return 0
}

func (x *AmneziaWGResponse) GetS1() int32 {
	if x != nil {
		return x.S1
	}
	return 0
}

func (x *AmneziaWGResponse) GetS2() int32 {
	if x != nil {
		return x.S2
	}
	return 0
}

func (x *AmneziaWGResponse) GetH1() int32 {
	if x != nil {
		return x.H1
	}
	return 0
}

func (x *AmneziaWGResponse) GetH2() int32 {
	if x != nil {
		return x.H2
	}
	return 0
}

func (x *AmneziaWGResponse) GetH3() int32 {
	if x != nil {
		return x.H3
	}
	return 0
}

func (x *AmneziaWGResponse) GetH4() int32 {
	if x != nil {
		return x.H4
	}
	return 0
}

type DeletePeerRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Protocol Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=agent.v1.Protocol" json:"protocol,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*DeletePeerRequest_PublicKey
	//	*DeletePeerRequest_Email
	Identifier    isDeletePeerRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePeerRequest) Reset() {
	*x = DeletePeerRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePeerRequest) ProtoMessage() {}

func (x *DeletePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePeerRequest.ProtoReflect.Descriptor instead.
func (*DeletePeerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DeletePeerRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *DeletePeerRequest) GetIdentifier() isDeletePeerRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *DeletePeerRequest) GetPublicKey() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeletePeerRequest_PublicKey); ok {
			return x.PublicKey
		}
	}
	return ""
}

func (x *DeletePeerRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*DeletePeerRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isDeletePeerRequest_Identifier interface {
	isDeletePeerRequest_Identifier()
}

type DeletePeerRequest_PublicKey struct {
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type DeletePeerRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*DeletePeerRequest_PublicKey) isDeletePeerRequest_Identifier() {}

func (*DeletePeerRequest_Email) isDeletePeerRequest_Identifier() {}

type DeletePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePeerResponse) Reset() {
	*x = DeletePeerResponse{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePeerResponse) ProtoMessage() {}

func (x *DeletePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePeerResponse.ProtoReflect.Descriptor instead.
func (*DeletePeerResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DeletePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetPeerBandwidthRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Protocol  Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=agent.v1.Protocol" json:"protocol,omitempty"`
	Bandwidth int32                  `protobuf:"varint,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*SetPeerBandwidthRequest_PublicKey
	//	*SetPeerBandwidthRequest_Email
	Identifier    isSetPeerBandwidthRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerBandwidthRequest) Reset() {
	*x = SetPeerBandwidthRequest{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerBandwidthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerBandwidthRequest) ProtoMessage() {}

func (x *SetPeerBandwidthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerBandwidthRequest.ProtoReflect.Descriptor instead.
func (*SetPeerBandwidthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SetPeerBandwidthRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *SetPeerBandwidthRequest) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *SetPeerBandwidthRequest) GetIdentifier() isSetPeerBandwidthRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *SetPeerBandwidthRequest) GetPublicKey() string {
	if x != nil {
		if x, ok := x.Identifier.(*SetPeerBandwidthRequest_PublicKey); ok {
			return x.PublicKey
		}
	}
	return ""
}

func (x *SetPeerBandwidthRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Identifier.(*SetPeerBandwidthRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isSetPeerBandwidthRequest_Identifier interface {
	isSetPeerBandwidthRequest_Identifier()
}

type SetPeerBandwidthRequest_PublicKey struct {
	PublicKey string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type SetPeerBandwidthRequest_Email struct {
	Email string `protobuf:"bytes,4,opt,name=email,proto3,oneof"`
}

func (*SetPeerBandwidthRequest_PublicKey) isSetPeerBandwidthRequest_Identifier() {}

func (*SetPeerBandwidthRequest_Email) isSetPeerBandwidthRequest_Identifier() {}

type SetPeerBandwidthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPeerBandwidthResponse) Reset() {
	*x = SetPeerBandwidthResponse{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPeerBandwidthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPeerBandwidthResponse) ProtoMessage() {}

func (x *SetPeerBandwidthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPeerBandwidthResponse.ProtoReflect.Descriptor instead.
func (*SetPeerBandwidthResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SetPeerBandwidthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bagent.v1\"\r\n" +
	"\vSyncRequest\":\n" +
	"\fSyncResponse\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.agent.v1.PeerConfigR\x05peers\"\\\n" +
	"\n" +
	"PeerConfig\x12.\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x12.agent.v1.ProtocolR\bprotocol\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"\xb1\x01\n" +
	"\fAgentMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\x06status\x18\x02 \x01(\v2\x15.agent.v1.AgentStatusH\x00R\x06status\x12F\n" +
	"\x10command_response\x18\x03 \x01(\v2\x19.agent.v1.CommandResponseH\x00R\x0fcommandResponseB\t\n" +
	"\acontent\"\xc6\x02\n" +
	"\x0eControlCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12>\n" +
	"\vcreate_peer\x18\x02 \x01(\v2\x1b.agent.v1.CreatePeerRequestH\x00R\n" +
	"createPeer\x12>\n" +
	"\vdelete_peer\x18\x03 \x01(\v2\x1b.agent.v1.DeletePeerRequestH\x00R\n" +
	"deletePeer\x12H\n" +
	"\rset_bandwidth\x18\x04 \x01(\v2!.agent.v1.SetPeerBandwidthRequestH\x00R\fsetBandwidth\x12A\n" +
	"\fhealth_check\x18\x05 \x01(\v2\x1c.agent.v1.HealthCheckRequestH\x00R\vhealthCheckB\b\n" +
	"\x06action\"\xbf\x02\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12G\n" +
	"\x0fcreate_response\x18\x03 \x01(\v2\x1c.agent.v1.CreatePeerResponseH\x00R\x0ecreateResponse\x12G\n" +
	"\x0fdelete_response\x18\x04 \x01(\v2\x1c.agent.v1.DeletePeerResponseH\x00R\x0edeleteResponse\x12S\n" +
	"\x12bandwidth_response\x18\x05 \x01(\v2\".agent.v1.SetPeerBandwidthResponseH\x00R\x11bandwidthResponseB\x06\n" +
	"\x04data\"\x14\n" +
	"\x12HealthCheckRequest\"0\n" +
	"\vAgentStatus\x12!\n" +
	"\factive_peers\x18\x01 \x01(\x05R\vactivePeers\"\xab\x01\n" +
	"\x11CreatePeerRequest\x12.\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x12.agent.v1.ProtocolR\bprotocol\x12\x1c\n" +
	"\tbandwidth\x18\x02 \x01(\x05R\tbandwidth\x12=\n" +
	"\rvless_options\x18\x03 \x01(\v2\x16.agent.v1.VLESSOptionsH\x00R\fvlessOptionsB\t\n" +
	"\aoptions\"\x1e\n" +
	"\fVLESSOptions\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaa\x01\n" +
	"\x12CreatePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\n" +
	"vless_data\x18\x02 \x01(\v2\x17.agent.v1.VLESSResponseH\x00R\tvlessData\x128\n" +
	"\bawg_data\x18\x03 \x01(\v2\x1b.agent.v1.AmneziaWGResponseH\x00R\aawgDataB\x06\n" +
	"\x04data\"\xed\x01\n" +
	"\rVLESSResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x10\n" +
	"\x03sni\x18\x04 \x01(\tR\x03sni\x12\x10\n" +
	"\x03pbk\x18\x05 \x01(\tR\x03pbk\x12\x10\n" +
	"\x03sid\x18\x06 \x01(\tR\x03sid\x12\x0e\n" +
	"\x02fp\x18\a \x01(\tR\x02fp\x12\x1c\n" +
	"\ttransport\x18\b \x01(\tR\ttransport\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\n" +
	" \x01(\tR\x04host\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode\"\xa1\x02\n" +
	"\x11AmneziaWGResponse\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x0e\n" +
	"\x02jc\x18\x05 \x01(\x05R\x02jc\x12\x12\n" +
	"\x04jmin\x18\x06 \x01(\x05R\x04jmin\x12\x12\n" +
	"\x04jmax\x18\a \x01(\x05R\x04jmax\x12\x0e\n" +
	"\x02s1\x18\b \x01(\x05R\x02s1\x12\x0e\n" +
	"\x02s2\x18\t \x01(\x05R\x02s2\x12\x0e\n" +
	"\x02h1\x18\n" +
	" \x01(\x05R\x02h1\x12\x0e\n" +
	"\x02h2\x18\v \x01(\x05R\x02h2\x12\x0e\n" +
	"\x02h3\x18\f \x01(\x05R\x02h3\x12\x0e\n" +
	"\x02h4\x18\r \x01(\x05R\x02h4\"\x8a\x01\n" +
	"\x11DeletePeerRequest\x12.\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x12.agent.v1.ProtocolR\bprotocol\x12\x1f\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tH\x00R\tpublicKey\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05emailB\f\n" +
	"\n" +
	"identifier\".\n" +
	"\x12DeletePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xae\x01\n" +
	"\x17SetPeerBandwidthRequest\x12.\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x12.agent.v1.ProtocolR\bprotocol\x12\x1c\n" +
	"\tbandwidth\x18\x02 \x01(\x05R\tbandwidth\x12\x1f\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tH\x00R\tpublicKey\x12\x16\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05emailB\f\n" +
	"\n" +
	"identifier\"4\n" +
	"\x18SetPeerBandwidthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*Q\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PROTOCOL_AMNEZIA_WG\x10\x01\x12\x12\n" +
	"\x0ePROTOCOL_VLESS\x10\x022\x8d\x01\n" +
	"\x13ControlPlaneService\x12?\n" +
	"\aConnect\x12\x16.agent.v1.AgentMessage\x1a\x18.agent.v1.ControlCommand(\x010\x01\x125\n" +
	"\x04Sync\x12\x15.agent.v1.SyncRequest\x1a\x16.agent.v1.SyncResponseB\x95\x01\n" +
	"\fcom.agent.v1B\n" +
	"AgentProtoP\x01Z8github.com/thebeyond-net/node-agent/pkg/agent/v1;agentv1\xa2\x02\x03AXX\xaa\x02\bAgent.V1\xca\x02\bAgent\\V1\xe2\x02\x14Agent\\V1\\GPBMetadata\xea\x02\tAgent::V1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agent_proto_goTypes = []any{
	(Protocol)(0),                    // 0: agent.v1.Protocol
	(*SyncRequest)(nil),              // 1: agent.v1.SyncRequest
	(*SyncResponse)(nil),             // 2: agent.v1.SyncResponse
	(*PeerConfig)(nil),               // 3: agent.v1.PeerConfig
	(*AgentMessage)(nil),             // 4: agent.v1.AgentMessage
	(*ControlCommand)(nil),           // 5: agent.v1.ControlCommand
	(*CommandResponse)(nil),          // 6: agent.v1.CommandResponse
	(*HealthCheckRequest)(nil),       // 7: agent.v1.HealthCheckRequest
	(*AgentStatus)(nil),              // 8: agent.v1.AgentStatus
	(*CreatePeerRequest)(nil),        // 9: agent.v1.CreatePeerRequest
	(*VLESSOptions)(nil),             // 10: agent.v1.VLESSOptions
	(*CreatePeerResponse)(nil),       // 11: agent.v1.CreatePeerResponse
	(*VLESSResponse)(nil),            // 12: agent.v1.VLESSResponse
	(*AmneziaWGResponse)(nil),        // 13: agent.v1.AmneziaWGResponse
	(*DeletePeerRequest)(nil),        // 14: agent.v1.DeletePeerRequest
	(*DeletePeerResponse)(nil),       // 15: agent.v1.DeletePeerResponse
	(*SetPeerBandwidthRequest)(nil),  // 16: agent.v1.SetPeerBandwidthRequest
	(*SetPeerBandwidthResponse)(nil), // 17: agent.v1.SetPeerBandwidthResponse
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: agent.v1.SyncResponse.peers:type_name -> agent.v1.PeerConfig
	0,  // 1: agent.v1.PeerConfig.protocol:type_name -> agent.v1.Protocol
	8,  // 2: agent.v1.AgentMessage.status:type_name -> agent.v1.AgentStatus
	6,  // 3: agent.v1.AgentMessage.command_response:type_name -> agent.v1.CommandResponse
	9,  // 4: agent.v1.ControlCommand.create_peer:type_name -> agent.v1.CreatePeerRequest
	14, // 5: agent.v1.ControlCommand.delete_peer:type_name -> agent.v1.DeletePeerRequest
	16, // 6: agent.v1.ControlCommand.set_bandwidth:type_name -> agent.v1.SetPeerBandwidthRequest
	7,  // 7: agent.v1.ControlCommand.health_check:type_name -> agent.v1.HealthCheckRequest
	11, // 8: agent.v1.CommandResponse.create_response:type_name -> agent.v1.CreatePeerResponse
	15, // 9: agent.v1.CommandResponse.delete_response:type_name -> agent.v1.DeletePeerResponse
	17, // 10: agent.v1.CommandResponse.bandwidth_response:type_name -> agent.v1.SetPeerBandwidthResponse
	0,  // 11: agent.v1.CreatePeerRequest.protocol:type_name -> agent.v1.Protocol
	10, // 12: agent.v1.CreatePeerRequest.vless_options:type_name -> agent.v1.VLESSOptions
	12, // 13: agent.v1.CreatePeerResponse.vless_data:type_name -> agent.v1.VLESSResponse
	13, // 14: agent.v1.CreatePeerResponse.awg_data:type_name -> agent.v1.AmneziaWGResponse
	0,  // 15: agent.v1.DeletePeerRequest.protocol:type_name -> agent.v1.Protocol
	0,  // 16: agent.v1.SetPeerBandwidthRequest.protocol:type_name -> agent.v1.Protocol
	4,  // 17: agent.v1.ControlPlaneService.Connect:input_type -> agent.v1.AgentMessage
	1,  // 18: agent.v1.ControlPlaneService.Sync:input_type -> agent.v1.SyncRequest
	5,  // 19: agent.v1.ControlPlaneService.Connect:output_type -> agent.v1.ControlCommand
	2,  // 20: agent.v1.ControlPlaneService.Sync:output_type -> agent.v1.SyncResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentMessage_Status)(nil),
		(*AgentMessage_CommandResponse)(nil),
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlCommand_CreatePeer)(nil),
		(*ControlCommand_DeletePeer)(nil),
		(*ControlCommand_SetBandwidth)(nil),
		(*ControlCommand_HealthCheck)(nil),
	}
	file_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*CommandResponse_CreateResponse)(nil),
		(*CommandResponse_DeleteResponse)(nil),
		(*CommandResponse_BandwidthResponse)(nil),
	}
	file_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*CreatePeerRequest_VlessOptions)(nil),
	}
	file_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*CreatePeerResponse_VlessData)(nil),
		(*CreatePeerResponse_AwgData)(nil),
	}
	file_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*DeletePeerRequest_PublicKey)(nil),
		(*DeletePeerRequest_Email)(nil),
	}
	file_agent_proto_msgTypes[15].OneofWrappers = []any{
		(*SetPeerBandwidthRequest_PublicKey)(nil),
		(*SetPeerBandwidthRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
